dist: bionic

language: node_js

node_js:
  - 12

env:
  global:
    - SA_PASSWORD=Password1
    - MSSQL_HOST=localhost
    - MSSQL_PORT=1433
    - MSSQL_USER=sa
    - MSSQL_PASSWORD=Password1
    - MSSQL_DB=sails-test

services:
  - docker

before_script:
  - sudo chmod 777 test/docker/*.sh
  - sudo ln -s /usr/bin/nodejs /usr/bin/node
  - which node
  - node --version
  - docker run --name=sqlserver -e ACCEPT_EULA=Y -e SA_PASSWORD=Password1 -p 1433:1433 -d mcr.microsoft.com/mssql/server:2017-latest-ubuntu
  - test/docker/wait-for-it.sh -t 120 localhost:1433 -- test/docker/travis-test.sh
