dist: bionic

language: node_js

node_js:
  - 12

env:
  global:
    - SA_PASSWORD=Password1
    - MSSQL_HOST=localhost
    - MSSQL_PORT=1433
    - MSSQL_USER=sa
    - MSSQL_PASSWORD=${SA_PASSWORD}
    - MSSQL_DB=sails-test

services:
  - docker

before_script:
  - docker run -d -e ACCEPT_EULA=Y -e SA_PASSWORD=$SA_PASSWORD -p 1433:1433 --name=sqlserver mcr.microsoft.com/mssql/server
  - docker cp test/docker/create-db.sh sqlserver:/tmp/
  - docker cp test/docker/sqlserver.setup.sql sqlserver:/tmp
  - docker cp test/docker/wait-for-it.sh sqlserver:/tmp
  - docker exec -it -u root sqlserver sh -c 'chmod 777 /tmp/*.sh'
  - docker exec -it -e SA_PASSWORD=$SA_PASSWORD sqlserver /tmp/wait-for-it.sh localhost:1433 -t 120 -- /tmp/create-db.sh
