language: node_js
node_js:
  - "12"
  - "14"
  - "16"
sudo: false
services:
  - postgresql
addons:
  postgresql: "9.4"
env:
  - DB_USER=mp DB_PASS='mp'
before_script:
  - psql -c 'create database mppg;' -U postgres
  - psql -c "create user mp with password 'mp';"
  - psql -c "grant all privileges on database mppg to mp;"
