dist: bionic

language: node_js

node_js:
  - 12

env:
  global:
    - SA_PASSWORD=Password1
    - MSSQL_HOST=localhost
    - MSSQL_PORT=1433
    - MSSQL_USER=sa
    - MSSQL_PASSWORD=Password1
    - MSSQL_DB=sails-test

services:
  - docker

before_install:
  - curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
  - curl https://packages.microsoft.com/config/ubuntu/18.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
  - sudo apt-get update
  - sudo apt-get install mssql-tools unixodbc-dev

before_script:
  - sudo chmod 777 test/docker/*.sh
  - sudo docker run --name=sqlserver -e ACCEPT_EULA=Y -e SA_PASSWORD=Password1 -p 1433:1433 -d mcr.microsoft.com/mssql/server:2017-latest-ubuntu
  - sudo test/docker/wait-for-it.sh -t 120 localhost:1433 -- test/docker/travis-test.sh
