language: node_js

node_js:
  - 10

env:
  global:
    - MSSQL_HOST=localhost
    - MSSQL_PORT=1433
    - MSSQL_USER=sa
    - MSSQL_PASSWORD=${SA_PASSWORD}
    - MSSQL_DB=sails-test

services:
  - docker

before_script:
  - sudo docker run --name=sqlserver -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=$SA_PASSWORD" -p 1433:1433 -d mcr.microsoft.com/mssql/server:2017-latest-ubuntu
  - sudo docker cp test/docker/. sqlserver:/tmp
  - sudo docker exec -it sqlserver /bin/bash -c 'chmod 777 /tmp/*.sh'
  - sudo docker exec -it sqlserver /tmp/wait-for-it.sh -t 120 localhost:1433 -- /tmp/travis-test.sh
